### ISSUE TITLE
Tracking issue: add missing endpoints

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/sauce-elixir#26]
Jobs endpoints to cover:
-------------------------------
- [ ] GET /v1.1/jobs/{id}                                         - Sauce.Jobs.get
- [ ] GET /v1.1/{username}/jobs                                   - Sauce.Jobs.get_user_jobs
- [ ] GET /v1/builds/{id}/jobs                                    - Sauce.Jobs.get_build_jobs
- [ ] GET /v1/{username}/builds/{id}/failed-jobs                  - Sauce.Jobs.get_build_failed_jobs
- [ ] GET /v1/{username}/jobs/{id}/assets                         - Sauce.Jobs.get_job_assets
- [ ] GET /v1/{username}/jobs/{id}/assets/{asset_file_name}       - Sauce.Jobs.get_job_asset_file
- [ ] PUT /v1/{username}/jobs/{id}/stop
- [ ] PUT /v1/{username}/jobs/{id}
- [ ] DEL /v1/{username}/jobs/{id}                                - Sauce.Jobs.delete
- [ ] DEL /v1/{username}/jobs/{id}/assets
